### PR TITLE
Add cloud sql proxy to admin tools deployment [Issue #263]

### LINKED ISSUE #263: Add cloud sql proxy to admin tools deployment
### Is your feature request related to a problem? Please describe.

Currently, The template adds a Cloud SQL proxy to the server deployment but does not add to the admin tools. so the admin tools cannot access the database by using the same proxy configuration likes the server deployment. Adding this to admin tools makes consistency for proxy connection and easy for using `temporal-cassandra-tool` and `temporal-sql-tool` inside the admin tools container.

### Describe the solution you'd like

Add the same Cloud SQL proxy sidecar configuration used for server deployment to the admin tools deployment.

### PR DESCRIPTION
**Pull request by skyfoxs**
## What was changed
Add Cloud SQL proxy sidecar to the admin tools deployment.

## Why?
To make Cloud SQL proxy available to the admin tools pod. So we can use the `temporal-cassandra-tool` and  `temporal-sql-tool` to connect to the database like the others deployed by `server-deployment.yaml` and don't have to build it on our machine.

## Checklist

1. Closes
Close #263 

2. How was this tested:
Set up and install with sidecar containers as usual. Then shell into admin-tools and connect database with `temporal-sql-tool`.

3. Any docs updates needed?
No

### CODE REVIEW

**Comment by tsurdilo** [comment]
@skyfoxs thanks for the PR!
Could you link it to an existing issue, or open a new one so it can be tracked? Thanks!

**Comment by skyfoxs** [comment]
> @skyfoxs thanks for the PR! Could you link it to an existing issue, or open a new one so it can be tracked? Thanks!

done

**Comment by tsurdilo** [comment]
This looks good to me. 
@underrun can you please also take a look? Thanks!

**Comment by mnichols** [comment]
Just wanted to point out this sidecar support (regardless of whether cloudsqlproxy is the intent) is already in other temporal service helm charts  (https://github.com/temporalio/helm-charts/pull/107).  Maybe that'll help merge it in :)

**Comment by kuzmik** [comment]
Any chance we can get this merged? I need it myself!

Also the sidecar is needed in the schema-setup jobs, since they require access to cloudsql as well; I'll see about adding that and making a PR for it.

**Comment by peter-c-larsson** [comment]
Any update on this and did you get around to making PR for the changes @kuzmik ?

**Comment by kuzmik** [comment]
> Any update on this and did you get around to making PR for the changes @kuzmik ?

We worked around it by adding extra sidecars in the jsonnet (we use argo to manage k8s deployments, and the jsonnet repo loads helm charts and adapts them via code).

Originally I had adapted this PR to include the sidecars https://github.com/temporalio/helm-charts/pull/259/files; but since we generally prefer not to modify the helm charts in our repo if we can avoid it, I converted it to the sonnet stuff.

```
local k = import 'ksonnet-util/kausal.libsonnet';

(import './config.libsonnet')
+ {
  local c = $._config.temporal,
  local deployment = k.apps.v1.deployment,

  temporal+: {
    deployment_temporal_admintools+:
      deployment.spec.template.spec.withContainersMixin(c.containerCSP)
      + deployment.spec.withMinReadySeconds(10)
      + c.mysqlCSISecretMount,
```

for example.

**Comment by robholland** [comment]
Please adjust this to add and use admintools.sidecarContainers instead.

**Comment by kuzmik** [comment]
> Please adjust this to add and use admintools.sidecarContainers instead.

looking at the charts on `main`, i don't see an entry for sidecarContainers under the admintools section in values.yaml

**Comment by robholland** [comment]
Closing due to inactivity. Please re-open if you'd like to adjust as requested.

**Pull request closed without merging**
