### PR TITLE
Automatically configure Postgres and MySQL databases on startup.

### LINKED ISSUE #349: [Feature Request] Add Kubernetes job to migrate postgresql schema
Currently, the helm chart only supports migrating schemas on Cassandra; I would like to add support for the same feature when bringing my own PostgreSQL

### Describe the solution you'd like

Add support for PostgreSQL for the following values in `values.yaml`

```
schema:
  setup:
    enabled: true
  update:
    enabled: true
```

### PR DESCRIPTION
**Pull request by rogersd**
## What was changed

Automatically create databases and apply the schemas to them for Postgres and MySQL.

## Why?

In order to be able to create new environments via Terraform without having to manually create the databases between the provisioning of the cluster and the deployment of the helm chart.

Closes #349

## Checklist

1. How was this tested:

I used this to provision a Postgres cluster, but no other testing has been done.  In particular, MySQL hasn't been tested at all.

2. Any docs updates needed?

Probably?  I'm just giving this back to hopefully help other people, but I don't have the time to do any more work on it myself.

### CODE REVIEW

**Comment by franklinkim** [comment]
Hi team, seems like duplicate of #275. Would love to see one of them merged

**Comment by gajus** [comment]
Added this patch to our branch, if anyone needs it:

https://github.com/contra/helm-charts/commit/ff0d75f302eb69106468a4d0f6f9bc2a006128a8

**Review by jeenadeepak — APPROVED** [review]

**Review by jeenadeepak — APPROVED** [review]

**Comment by NoUseFreak** [comment]
I can confirm this works. Can this get merged?

**Comment by NoUseFreak** [comment]
@rogersd I think you need to sign the Contributor License Agreement https://cla-assistant.io/temporalio/helm-charts?pullRequest=281

**Comment by medamineamara** [comment]
This PR will close this issue
https://github.com/temporalio/helm-charts/issues/349

**Comment by rogersd** [comment]
> @rogersd I think you need to sign the Contributor License Agreement https://cla-assistant.io/temporalio/helm-charts?pullRequest=281

I’ve signed it, but I’m not sure if there’s something that needs to be done for GitHub to pick that up?

**Comment by NoUseFreak** [comment]
@jeenadeepak What needs to happen to pass the cla?

**Comment by foogazy** [comment]
Anyway we can help with this being approved?

**Comment by mindaugasrukas** [comment]
I'm taking over this PR.

**Comment by rogersd** [comment]
> I'm taking over this PR.

Thanks, @mindaugasrukas !

**Comment by mindaugasrukas** [comment]
I'm closing this in favor of #405
I had to fix commands, but overall everything is ok.

**Pull request closed without merging**
