### PR TITLE
add new options for TEMPORAL_CORS_ORIGINS and TEMPORAL_CSRF_COOKIE_INSECURE

### LINKED ISSUE #401: [Feature Request] Add TEMPORAL_CSRF_COOKIE_INSECURE and TEMPORAL_CORS_ORIGINS options
# Brief description

Allow `TEMPORAL_CSRF_COOKIE_INSECURE` and `TEMPORAL_CORS_ORIGINS` to be specified for the ui container

### PR DESCRIPTION
**Pull request by danthegoodman1**
## What was changed

Adds options for `TEMPORAL_CORS_ORIGINS` and `TEMPORAL_CSRF_COOKIE_INSECURE`

## Why?

So they can be configured more explicitly than through the `additionalEnvs`, lacking documentation on them so surfacing to dedicated options makes it easier to find the functionality. Also this usage is quite common for privately-networked deployments.

## Checklist

1. Closes  #401 

2. How was this tested:

`helm template`

3. Any docs updates needed?

No

### CODE REVIEW

**Review by tsurdilo — APPROVED** [review]

**Comment by danthegoodman1** [comment]
@tsurdilo what's needed to merge this?

**Comment by karelbilek** [comment]
@tsurdilo this would be very helpful

**Comment by karelbilek** [comment]
How will this work with multiple cors origins? I am trying to decode how is UI config separating them and I don't really understand all the pieces involved

**Comment by karelbilek** [comment]
I see the env name is `TEMPORAL_CORS_ORIGINS` so I guess multiple is possible

but I also see this in the conf template in ui repo

```
  allowOrigins:
    # override framework's default that allows all origins "*"
    - {{ default .Env.TEMPORAL_CORS_ORIGINS "http://localhost:8080" }}
  ```

this seems like the value is just put into single value list? Not sure

**Comment by karelbilek** [comment]
It was fixed here

https://github.com/temporalio/ui/pull/1572

**Comment by jphilippelingrand** [comment]
Should we close this MR?

**Comment by robholland** [comment]
A link to the web UI config docs is now included in the values.yaml. I don't think we should special case these.

**Pull request closed without merging**
