### PR TITLE
Pass SQL configuration env variables to schema update & setup jobs

### LINKED ISSUE #310: [Bug] Schema setup & update jobs do not work for MySQL
### What are you really trying to do?

Use the schema setup & update jobs to initialize the temporal & temporal_visibility schemas. 

### Describe the bug
Enabling either schema setup or update jobs fails with an error indicating that the job cannot connect to the SQL database. 

```bash
2022-08-05T23:19:28.104Z	ERROR	Unable to connect to SQL database.	{"error": "dial tcp 127.0.0.1:3306: connect: connection refused", "logging-call-at": "handler.go:54"}
```

Screen Shot 2022-08-05 at 4 35 16 PM

### Minimal Reproduction

1. Update values/values.mysql.yaml with the appropriate credentials to connect to a SQL database (username, password, etc)
2. Run
    ```sh
    helm install -f values/values.mysql.yaml temporaltest \
      --set schema.setup.enabled=true \
      --set schema.update.enabled=true . --timeout 900s
    ```

### Additional context
The root cause of the issue is that the SQL configuration parameters are not passed as environment variables. As described in [install-with-your-own-mysql](https://github.com/temporalio/helm-charts#install-with-your-own-mysql) we need environment variables such as SQL_USER, SQL_PASSWORD, SQL_HOST to be specified. 

We can see that in the generated YAML the list of environment variables is empty
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: temporaltest-schema-setup
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.17.2
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: temporaltest
    app.kubernetes.io/version: 1.17.2
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: temporal
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 100
  template:
    metadata:
      name: temporaltest-schema-setup
      labels:
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-0.17.2
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: temporaltest
        app.kubernetes.io/version: 1.17.2
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: temporal
    spec:
      
      restartPolicy: "OnFailure"
      initContainers:
          []
      containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.17.2"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:
        - name: visibility-schema
          image: "temporalio/admin-tools:1.17.2"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:

```

### PR DESCRIPTION
**Pull request by fivos**
## What was changed
Update server-job.yaml to include the required environment variables to connect to a SQL database.

## Why?
With MySQL used as the persistence store, the schema setup & update jobs failed to connect to the database. 

## Checklist

1. Closes  #310

2. How was this tested:

#### Generate YAML
```bash
helm template -f values/values.mysql.yaml temporaltest \
  --set schema.setup.enabled=true \
  --set schema.update.enabled=true \
  --set server.config.persistence.default.sql.user=DEFAULT_USER \
  --set server.config.persistence.default.sql.password=DEFAULT_PASSWORD \
  --set server.config.persistence.default.sql.host=DEFAULT_HOST \
  --set server.config.persistence.visibility.sql.user=VISIBILITY_USER \
  --set server.config.persistence.visibility.sql.password=VISIBILITY_PASSWORD \
  --set server.config.persistence.visibility.sql.host=VISIBILITY_HOST .
```

#### Schema Setup
```yaml
# Source: temporal/templates/server-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: temporaltest-schema-setup
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.17.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: temporaltest
    app.kubernetes.io/version: 1.17.1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: temporal
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 100
  template:
    metadata:
      name: temporaltest-schema-setup
      labels:
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-0.17.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: temporaltest
        app.kubernetes.io/version: 1.17.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: temporal
    spec:
      
      restartPolicy: "OnFailure"
      initContainers:
          []
      containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_HOST
              value: DEFAULT_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: DEFAULT_USER
            - name: SQL_PASSWORD
              value: DEFAULT_PASSWORD
        - name: visibility-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: SQL_DATABASE
              value: temporal_visibility
            - name: SQL_HOST
              value: VISIBILITY_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: VISIBILITY_USER
            - name: SQL_PASSWORD
              value: VISIBILITY_PASSWORD
```

####  Schema Update
```yaml
# Source: temporal/templates/server-job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: temporaltest-schema-update
  labels:
    app.kubernetes.io/name: temporal
    helm.sh/chart: temporal-0.17.1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: temporaltest
    app.kubernetes.io/version: 1.17.1
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: temporal
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  backoffLimit: 100
  template:
    metadata:
      name: temporaltest-schema-update
      labels:
        app.kubernetes.io/name: temporal
        helm.sh/chart: temporal-0.17.1
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/instance: temporaltest
        app.kubernetes.io/version: 1.17.1
        app.kubernetes.io/component: database
        app.kubernetes.io/part-of: temporal
    spec:
      
      restartPolicy: "OnFailure"
      initContainers:
          []
      containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: [ 'temporal-sql-tool', 'update', '-schema-dir', 'schema/mysql/v57/temporal/versioned' ]
          env:
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_HOST
              value: DEFAULT_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: DEFAULT_USER
            - name: SQL_PASSWORD
              value: DEFAULT_PASSWORD
        - name: visibility-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: [ 'temporal-sql-tool', 'update', '-schema-dir', 'schema/mysql/v57/visibility/versioned' ]
          env:
            - name: SQL_DATABASE
              value: temporal_visibility
            - name: SQL_HOST
              value: VISIBILITY_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: VISIBILITY_USER
            - name: SQL_PASSWORD
              value: VISIBILITY_PASSWORD
```

#### Generate YAML

```bash
helm template -f values/values.mysql.yaml temporaltest \
  --set schema.setup.enabled=true \
  --set schema.update.enabled=true \
  --set server.config.persistence.default.sql.user=DEFAULT_USER \
  --set server.config.persistence.default.sql.existingSecret=DEFAULT_SECRET \
  --set server.config.persistence.default.sql.host=DEFAULT_HOST \
  --set server.config.persistence.visibility.sql.user=VISIBILITY_USER \
  --set server.config.persistence.visibility.sql.existingSecret=VISIBILITY_SECRET \
  --set server.config.persistence.visibility.sql.host=VISIBILITY_HOST . 
```

#### Schema setup
```yaml
containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_HOST
              value: DEFAULT_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: DEFAULT_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: DEFAULT_SECRET
                  key: password
        - name: visibility-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: ["temporal-sql-tool", "setup-schema", "-v", "0.0"]
          env:
            - name: SQL_DATABASE
              value: temporal_visibility
            - name: SQL_HOST
              value: VISIBILITY_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: VISIBILITY_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: VISIBILITY_SECRET
                  key: password
```

#### Schema Update

```yaml
containers:
        - name: default-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: [ 'temporal-sql-tool', 'update', '-schema-dir', 'schema/mysql/v57/temporal/versioned' ]
          env:
            - name: SQL_DATABASE
              value: temporal
            - name: SQL_HOST
              value: DEFAULT_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: DEFAULT_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: DEFAULT_SECRET
                  key: password
        - name: visibility-schema
          image: "temporalio/admin-tools:1.17.1"
          imagePullPolicy: IfNotPresent
          command: [ 'temporal-sql-tool', 'update', '-schema-dir', 'schema/mysql/v57/visibility/versioned' ]
          env:
            - name: SQL_DATABASE
              value: temporal_visibility
            - name: SQL_HOST
              value: VISIBILITY_HOST
            - name: SQL_PORT
              value: "3306"
            - name: SQL_USER
              value: VISIBILITY_USER
            - name: SQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: VISIBILITY_SECRET
                  key: password
```

3. Any docs updates needed?
No

### CODE REVIEW

**Comment by tsurdilo** [comment]
looking into this pr. ty

**Comment by pfragoso** [comment]
It would be great if this "sql" also worked with PostgreSQL schemas. It's mostly the same but the path it's different ie postgresql/v96

**Comment by fivos** [comment]
@pfragoso I updated the PR to use the right path for Postgres

**Comment by pzduniak** [comment]
Temporal folks - can we please get this one merged? If the author of this PR does not have time to rebase it, I can do it.

We're trying to normalize our Temporal deployments, now that most of our issues with the Helm chart from year+ ago are solved, and this is the last critical issue stopping us from not having to patch the output of your chart. Even worse, this behavior is completely undocumented.

Regardless of the actions of Temporal here, we'll _probably_ end up merging it into our fork and [publishing it in our Temporal Helm repo](https://pyr-sh.github.io/temporal-helm-charts/index.yaml).

**Comment by omercnet** [comment]
@fivos can you approve this? Any other work required here?


Happy to pitch in just let me know

**Comment by fivos** [comment]
@omercnet there shouldn't be any other work required. We have this tested and running in our copy of the Temporal helm chart at least. I can't approve my own PR though.  I'm happy to support this PR and make changes if needed but I'm still waiting on feedback from the Temporal folks.

**Comment by omercnet** [comment]
Oh sorry, tagged you as the last file contributor, didn't realize you're the OP here 

@alexshtin @wxing1292 Can we get some love here?

**Comment by omercnet** [comment]
@antmendoza @yux0 

Sorry for the spam, but this is a significant update that is been stale for a couple of months

**Comment by omercnet** [comment]
@dnr 🙏 ?

**Comment by tsurdilo** [comment]
Hi @omercnet thanks for the ping. We haven't had the chance to review and test this pr yet. Planning to do this as soon as possible. 
Could you for the time being please apply the pr locally and use it? Thanks.

**Comment by thjwhite** [comment]
Hello, wondering if anyone from the Temporal team side has looked at this PR? My team is also looking to use postgres backed Temporal and this would be very beneficial to automating the install/upgrade steps.

**Review by deepakjeena — APPROVED** [review]
seems ok

**Review by omercnet — APPROVED** [review]

**Comment by basgys** [comment]
I tested the patch and the basic setup looks good. However, the `tls` parameters are not supported.

```shell
--set server.config.persistence.default.sql.tls.enabled=true \
--set server.config.persistence.default.sql.tls.enableHostVerification=true \
--set server.config.persistence.visibility.sql.tls.enabled=true \
--set server.config.persistence.visibility.sql.tls.enableHostVerification=true \
...
```

**Comment by danielhomer** [comment]
+1 would really like to see this merged

**Review by jeenadeepak — APPROVED** [review]

**Review by jeenadeepak — APPROVED** [review]
seems ok.

**Comment by fivos** [comment]
https://github.com/temporalio/helm-charts/pull/405/ was recently merged which addressed the same issue. 

There's also an open PR for the TLS parameters https://github.com/temporalio/helm-charts/pull/411/files

Closing this one as it's no longer needed.

**Pull request closed without merging**
