### PR TITLE
Add support for ISTIO sidecar

### PR DESCRIPTION
**Pull request by jeenadeepak**
## What was changed

Add support for ISTIO deployment

## Why?

Istio run with each pod due to which one time job/pod are not successfully terminal, istio is not required here as db schema setup and update are one time job, hence skipping istio for jobs.

## Checklist

1. Closes 
 #https://github.com/temporalio/helm-charts/issues/353

2. How was this tested:

Testing on AWS EKS with istio.

3. Any docs updates needed?

no

### CODE REVIEW

**Comment by mindaugasrukas** [comment]
Please make these optional via `extraAnnotations` value.
As an example, see https://github.com/temporalio/helm-charts/blob/master/templates/serviceaccount.yaml#L16.

**Review by mindaugasrukas — CHANGES_REQUESTED** [review]
Please make these optional via `extraAnnotations` value.
As an example, see https://github.com/temporalio/helm-charts/blob/master/templates/serviceaccount.yaml#L16.

**Comment by jeenadeepak** [comment]
@mindaugasrukas : I have checked this example, it does not seems correct solution.

I am facing this issue with DB migration job due to istio, rest service are working fine with istio, so I do not want remove istio for entire application, but as per this example this will skip istio for other temporal services.

There are 2 problem I have identified with DB migration:
1: DB migration is one time job, hence db migration container quit but istio container is log running so it showing error, 
2: DB migration started before istio networking hence it stop DB migration container to connect with SQL port.

**Comment by mindaugasrukas** [comment]
My point is that this change will add environment-specific fields to the generic template. We don't want to add every environment-specific setting to the template but have the ability to inject user-specific configs. So, I'd like to ask you to make the template change, allowing you or anyone else to inject their needs.

**Comment by vishwa-trulioo** [comment]
Any update on this?

**Pull request closed without merging**
