### PR TITLE
Publish temporal chart

### LINKED ISSUE #45: Publish temporal helm chart to a helm chart repository (e. g. Helm Hub)
Please publish Temporal Helm chart to a helm chart repository (such as [Helm Hub](https://hub.helm.sh/charts)), so it is easier to install it.

[Brought to our attention](https://community.temporal.io/t/is-the-helm-chart-published-to-a-helm-repository-somewhere/182?u=markmark) by Kyle, thank you!

### PR DESCRIPTION
**Pull request by joebowbeer**
Fixes #45 

Changes:
* Move chart content (16 file renames) to `charts/temporal` folder
* Add chart-release workflow to publish on push to master branch
* Bump helm chart to version 0.2.4

**NOTE**: The `helm/chart-releaser` tool depends on the existence of a `gh-pages` branch. This should be created manually in [temporalio/helm-charts](https://github.com/temporalio/helm-charts) repo prior to merging this PR.

### CODE REVIEW

**Comment by sagikazarmark** [comment]
You might want to use a vanity domain, like `charts.temporal.io`.

**Comment by joebowbeer** [comment]
@sagikazarmark Good point, though the vanity domain can be added or not separately. It doesn't need to affect publication script.

For example, localstack publishes helm charts to http://localstack.github.io/helm-charts via gh-pages, and the charts repo can also be installed as http://helm.localstack.cloud/

**Comment by joebowbeer** [comment]
rebased onto chart 0.2.3 
@underrun PTAL

**Comment by underrun** [comment]
@joebowbeer I love this concept and we will definitely want to do this, but it's blocked on another more significant change: breaking apart the helm chart into one that only installs and configures temporal itself (which will be our production helm chart) and another that combines the separate temporal helm chart and charts for dependencies into something more like what we have today (and which we name clearly as a development chart).

part of the problem today is that there are production pieces and development pieces in the same chart and that's made it difficult to message about. if we're going to create a first class helm experience it really needs to start by having a chart we can say is entirely production ready without any caveats.

I've created an issue describing this: https://github.com/temporalio/helm-charts/issues/189

**Comment by underrun** [comment]
Closing this for now as we will take a different approach to releasing the chart after our new approach to helm charts is implemented: https://github.com/temporalio/proposals/issues/42

**Pull request closed without merging**
