### PR TITLE
fixed indentations in ingress

### PR DESCRIPTION
**Pull request by saurabnigam**

### CODE REVIEW

**Comment by markmark206** [comment]
Thank you for the submission, @saurabnigam ! 

And thank you for your patience – we have seen a couple of submissions for this problem (https://github.com/temporalio/helm-charts/pull/41 and https://github.com/temporalio/helm-charts/pull/33 -- thank you @ruanwz and @yvanin, and apologies for the slow follow up on this!).

If you happened to have to have a sample `values.yaml` or a `helm install ...` (or `template`) command line that reproduces the problem you that could share with us, please send it our way! This would help us quickly test the fix, and to add a test to our test pipeline.

Thank you!

**Comment by saurabnigam** [comment]
**Command:**
 helm install --dry-run  -n=temporal -f values/values.elasticsearch.yaml -f values/values.cassandra.yaml  --set prometheus.enabled=false --set grafana.enabled=false  --set kafka.enabled=false  --set server.kafka.host=kafka-headless.kafka:29092 temporal . --timeout 900s 

**Error** 

Error: YAML parse error on temporal/templates/web-ingress.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key


**Sample Values.yaml**
nameOverride: ""
fullnameOverride: ""

# Chart debug mode
# (eg. disable helm hook delete policy)
debug: false

server:
  enabled: true
  image:
    repository: temporalio/server
    tag: 1.1.1
    pullPolicy: IfNotPresent

  kafka:
    host:

  # Global default settings (can be overridden per service)
  replicaCount: 1
  metrics:
    # Annotate pods directly with Prometheus annotations.
    # Use this if you installed Prometheus from a Helm chart.
    annotations:
      enabled: true
    # Enable Prometheus ServiceMonitor
    # Use this if you installed the Prometheus Operator (https://github.com/coreos/prometheus-operator).
    serviceMonitor:
      enabled: false
      interval: 30s
    prometheus:
      timerType: histogram
  podAnnotations: {}
  resources:
    {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}

  config:
    logLevel: "debug,info"

    # IMPORTANT: This value cannot be changed, once it's set.
    numHistoryShards: 512

    persistence:
      default:
        driver: "cassandra"

        cassandra:
          hosts: []
          # port: 9042
          keyspace: temporal
          user: "user"
          password: "password"
          existingSecret: ""
          replicationFactor: 1
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"
          # datacenter: "us-east-1a"
          # maxQPS: 1000
          # maxConns: 2

        sql:
          driver: "mysql"
          host: "mysql"
          port: 3306
          database: temporal
          user: "temporal"
          password: "temporal"
          existingSecret: ""
          secretName: ""

      visibility:
        driver: "cassandra"

        cassandra:
          hosts: []
          # port: 9042
          keyspace: temporal_visibility
          user: "user"
          password: "password"
          existingSecret: ""
          # datacenter: "us-east-1a"
          # maxQPS: 1000
          # maxConns: 2
          replicationFactor: 1
          consistency:
            default:
              consistency: "local_quorum"
              serialConsistency: "local_serial"

        sql:
          driver: "mysql"
          host: "mysql"
          port: 3306
          database: temporal_visibility
          user: "temporal"
          password: "temporal"
          existingSecret: ""
          secretName: ""

  frontend:
    # replicaCount: 1
    service:
      type: ClusterIP
      port: 7233
    metrics:
      annotations:
        enabled: true
      serviceMonitor: {}
      # enabled: false
      prometheus: {}
      # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  history:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7934
    metrics:
      annotations:
        enabled: true
      serviceMonitor: {}
      # enabled: false
      prometheus: {}
      # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  matching:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7935
    metrics:
      annotations:
        enabled: false
      serviceMonitor: {}
      # enabled: false
      prometheus: {}
      # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  worker:
    # replicaCount: 1
    service:
      # type: ClusterIP
      port: 7239
    metrics:
      annotations:
        enabled: true
      serviceMonitor: {}
      # enabled: false
      prometheus: {}
      # timerType: histogram
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

admintools:
  enabled: true
  image:
    repository: temporalio/admin-tools
    tag: 1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 22
    annotations: {}

web:
  enabled: true

  replicaCount: 1

  image:
    repository: temporalio/web
    tag: 1.1.1
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8088
    annotations: {}
    # loadBalancerIP:


  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: demo
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
      ingress.kubernetes.io/ssl-redirect: "true"
    hosts:
      - "temporal-deomtest.co"
      # - "domain.com/xyz"
      # - "domain.com"
    tls:
      - secretName: temporal-tls
        hosts:
          - temporal-deomtest.co

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

schema:
  setup:
    enabled: true
    backoffLimit: 100
  update:
    enabled: true
    backoffLimit: 100

elasticsearch:
  enabled: true
  replicas: 3
  persistence:
    enabled: false
  imageTag: 6.8.8
  host: elasticsearch-master-headless
  scheme: http
  port: 9200

prometheus:
  enabled: true
  nodeExporter:
    enabled: false

kafka:
  enabled: true

grafana:
  enabled: true
  replicas: 1
  testFramework:
    enabled: false
  rbac:
    create: false
    pspEnabled: false
    namespaced: true
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/default
  datasources:
   datasources.yaml:
     apiVersion: 1
     datasources:
     - name: TemporalMetrics
       type: prometheus
       url: http://{{ .Release.Name }}-prometheus-server
       access: proxy
       isDefault: true
  dashboards:
     default:
       frontend-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/frontend.json
         datasource: TemporalMetrics
       temporal-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/temporal.json
         datasource: TemporalMetrics
       history-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/history.json
         datasource: TemporalMetrics
       matching-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/matching.json
         datasource: TemporalMetrics
       clusteroverview-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/10000.json
         datasource: TemporalMetrics
       common-github:
         url: https://raw.githubusercontent.com/temporalio/temporal-dashboards/master/dashboards/common.json
         datasource: TemporalMetrics

cassandra:
  enabled: true
  persistence:
    enabled: false
  image:
    repo: cassandra
    tag: 3.11.3
    pullPolicy: IfNotPresent
  config:
    cluster_size: 3
    ports:
      cql: 9042
    num_tokens: 4
    max_heap_size: 512M
    heap_new_size: 128M
    seed_size: 0
  service:
    type: ClusterIP

mysql:
  enabled: false

**Comment by lerminou** [comment]
got the same error I use the default helm with juste this line changed:
```
  ingress:
    enabled: true
```

**Comment by underrun** [comment]
Cannot reproduce and the helm charts will change going forward so any solution to this will be different after the change. See here for more details: https://github.com/temporalio/proposals/issues/42

**Pull request closed without merging**
